on:
  - push
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: sync to s3
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            --acl public-read \
            build s3://junction.sangmin.in

      - name: invalid cache
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_KEY }}'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3GZYXKWFZ4MYK \
            --paths "/*"
